language: node_js
node_js:
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
script: npm run test-cli
sudo: false
jobs:
  include:
    - stage: linting
      script: npm run lint
    - stage: checks
      script: npm run check
    - stage: security
      script: npm i --package-lock-only && npm audit
