language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
  - '4'
  - '5'
  - '6'
script: npm run test:integration
sudo: false
jobs:
  include:
    - stage: linting
      node_js: 6
      script: npm run test:lint
    - stage: security
      node_js: 6
      script: npm i -g npm@6 && npm i --package-lock-only && npm audit
